#!/usr/bin/env php
<?php
// File: sushi

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application('Sushi', '1.0.0');
$HelloCommand = new \Commands\Hello();
$application->add($HelloCommand);
$application->run();
